import { District, Zone, PollingStation, Candidate, Party, PollingStationVote } from './types';

export const INITIAL_PARTIES: Party[] = [
  {
    id: 'p1',
    name: 'พรรคประชาชน',
    shortName: 'ปชช.',
    color: '#FF6600',
  },
  {
    id: 'p2',
    name: 'พรรคเพื่อไทย',
    shortName: 'พท.',
    color: '#E60000',
  },
  {
    id: 'p3',
    name: 'พรรคภูมิใจไทย',
    shortName: 'ภท.',
    color: '#0A2540',
  },
  {
    id: 'p4',
    name: 'พรรคประชาธิปัตย์',
    shortName: 'ปชป.',
    color: '#00A3E0',
  },
  {
    id: 'p5',
    name: 'พรรครวมไทยสร้างชาติ',
    shortName: 'รทสช.',
    color: '#1C355E',
  },
  {
    id: 'p6',
    name: 'พรรคก้าวไกลเดิม/อิสระ',
    shortName: 'อิสระ',
    color: '#059669',
  },
];

export const INITIAL_DISTRICTS: District[] = [
  { id: 'd1', name: 'อำเภอเมืองเชียงใหม่', code: 'MUEANG' },
  { id: 'd2', name: 'อำเภอแม่ริม', code: 'MAE_RIM' },
  { id: 'd3', name: 'อำเภอสารภี', code: 'SARAPHI' },
  { id: 'd4', name: 'อำเภอหางดง', code: 'HANG_DONG' },
];

export const INITIAL_ZONES: Zone[] = [
  { id: 'z1', name: 'เขตเลือกตั้งที่ 1 (เทศบาลนครเชียงใหม่)', zoneNumber: 1, districtId: 'd1' },
  { id: 'z2', name: 'เขตเลือกตั้งที่ 2 (ช้างเผือก - สุเทพ - แม่ริม)', zoneNumber: 2, districtId: 'd2' },
  { id: 'z3', name: 'เขตเลือกตั้งที่ 3 (สารภี - หางดง)', zoneNumber: 3, districtId: 'd3' },
];

export const INITIAL_POLLING_STATIONS: PollingStation[] = [
  {
    id: 's1',
    name: 'หน่วยที่ 1 หอประชุมหอศิลป์ มช. (ต.สุเทพ)',
    stationNumber: 1,
    districtId: 'd1',
    zoneId: 'z1',
    totalEligibleVoters: 1250,
    status: 'in_progress',
  },
  {
    id: 's2',
    name: 'หน่วยที่ 2 โรงเรียนยุพราชวิทยาลัย (ต.ศรีภูมิ)',
    stationNumber: 2,
    districtId: 'd1',
    zoneId: 'z1',
    totalEligibleVoters: 1100,
    status: 'in_progress',
  },
  {
    id: 's3',
    name: 'หน่วยที่ 3 ศาลาอ่างแก้ว (ต.สุเทพ)',
    stationNumber: 3,
    districtId: 'd1',
    zoneId: 'z1',
    totalEligibleVoters: 980,
    status: 'completed',
  },
  {
    id: 's4',
    name: 'หน่วยที่ 1 วัดป่าดอนแก้ว (ต.ดอนแก้ว อ.แม่ริม)',
    stationNumber: 1,
    districtId: 'd2',
    zoneId: 'z2',
    totalEligibleVoters: 1050,
    status: 'in_progress',
  },
  {
    id: 's5',
    name: 'หน่วยที่ 2 อาคารเอนกประสงค์เทศบาลแม่ริม',
    stationNumber: 2,
    districtId: 'd2',
    zoneId: 'z2',
    totalEligibleVoters: 1300,
    status: 'in_progress',
  },
  {
    id: 's6',
    name: 'หน่วยที่ 1 โรงเรียนสารภีพิทยาคม (ต.ยางเนิ้ง)',
    stationNumber: 1,
    districtId: 'd3',
    zoneId: 'z3',
    totalEligibleVoters: 1150,
    status: 'in_progress',
  },
  {
    id: 's7',
    name: 'หน่วยที่ 2 วัดยางเนิ้ง (ต.ยางเนิ้ง อ.สารภี)',
    stationNumber: 2,
    districtId: 'd3',
    zoneId: 'z3',
    totalEligibleVoters: 890,
    status: 'pending',
  },
  {
    id: 's8',
    name: 'หน่วยที่ 1 หอประชุมอำเภอหางดง (ต.หางดง)',
    stationNumber: 1,
    districtId: 'd4',
    zoneId: 'z3',
    totalEligibleVoters: 1400,
    status: 'in_progress',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'c1',
    number: 1,
    name: 'ดร.ณัฐพงษ์ เพชรลดา',
    partyId: 'p1',
    partyName: 'พรรคประชาชน',
    partyColor: '#FF6600',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    bio: 'วิศวกรการเมือง อดีตนักวิจัยพัฒนาเมือง นโยบายสมาร์ทซิตี้และการคมนาคม',
  },
  {
    id: 'c2',
    number: 2,
    name: 'นายกิตติศักดิ์ พัฒนชัย',
    partyId: 'p2',
    partyName: 'พรรคเพื่อไทย',
    partyColor: '#E60000',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    bio: 'ผู้ประกอบการท้องถิ่น อดีตรองนายกเทศมนตรีนครเชียงใหม่ นโยบายฟื้นฟูเศรษฐกิจ',
  },
  {
    id: 'c3',
    number: 3,
    name: 'นางสาวศิริพร บุญเจริญ',
    partyId: 'p3',
    partyName: 'พรรคภูมิใจไทย',
    partyColor: '#0A2540',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    bio: 'ผู้เชี่ยวชาญด้านสาธารณสุขและการท่องเที่ยวชุมชน นโยบายยกระดับ รพ.สต.',
  },
  {
    id: 'c4',
    number: 4,
    name: 'นายเฉลิมพล วงศ์สว่าง',
    partyId: 'p4',
    partyName: 'พรรคประชาธิปัตย์',
    partyColor: '#00A3E0',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    bio: 'ทนายความความบำนาญ นักกิจกรรมเพื่อสิ่งแวดล้อมและแก้ปัญหาน้ำท่วม',
  },
  {
    id: 'c5',
    number: 5,
    name: 'พันเอกสมชาย ชัยชนะ',
    partyId: 'p5',
    partyName: 'พรรครวมไทยสร้างชาติ',
    partyColor: '#1C355E',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400',
    bio: 'อดีตผู้บังคับการมณฑลทหารบก นโยบายความมั่นคงและความสงบเรียบร้อย',
  },
];

export const INITIAL_VOTES: PollingStationVote[] = [
  {
    stationId: 's1',
    candidateVotes: { c1: 420, c2: 310, c3: 145, c4: 65, c5: 40 },
    invalidVotes: 25,
    noVotes: 35,
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 1',
  },
  {
    stationId: 's2',
    candidateVotes: { c1: 380, c2: 295, c3: 110, c4: 45, c5: 30 },
    invalidVotes: 18,
    noVotes: 22,
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 2',
  },
  {
    stationId: 's3',
    candidateVotes: { c1: 450, c2: 210, c3: 95, c4: 50, c5: 25 },
    invalidVotes: 15,
    noVotes: 20,
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 3',
  },
  {
    stationId: 's4',
    candidateVotes: { c1: 290, c2: 340, c3: 160, c4: 70, c5: 55 },
    invalidVotes: 30,
    noVotes: 15,
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 1 (แม่ริม)',
  },
  {
    stationId: 's5',
    candidateVotes: { c1: 310, c2: 280, c3: 190, c4: 85, c5: 60 },
    invalidVotes: 22,
    noVotes: 18,
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 2 (แม่ริม)',
  },
  {
    stationId: 's6',
    candidateVotes: { c1: 340, c2: 320, c3: 150, c4: 50, c5: 45 },
    invalidVotes: 20,
    noVotes: 25,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 1 (สารภี)',
  },
  {
    stationId: 's7',
    candidateVotes: { c1: 0, c2: 0, c3: 0, c4: 0, c5: 0 },
    invalidVotes: 0,
    noVotes: 0,
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedBy: '-',
  },
  {
    stationId: 's8',
    candidateVotes: { c1: 390, c2: 410, c3: 200, c4: 80, c5: 75 },
    invalidVotes: 35,
    noVotes: 40,
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString(),
    updatedBy: 'เจ้าหน้าที่ประจำหน่วยที่ 1 (หางดง)',
  },
];
